server:
    port: 8084

stripe:
    secret-key: sk_test_51Kiay7IDTHvo6Uv1StroqjLzgB1JcAAmlTNjROpsuroEVTj6Rlwd5KpBWgYxQFaPe5873qQx9nZ8eDvRY100Lhtc00KeUjT7BW
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/co-ride
        username: postgres
        password: admin
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
    flyway:
        locations:
          - classpath:db/migration